stages:
  - test

variables:
  PIP_DOWNLOAD_CACHE: "/cache/python-pip"
  COMPOSER_CACHE_DIR: "/cache/php-composer"


.temp: &temp
  stage: test
  image: python:3.7
  dependencies: []
  before_script:
    - apt-get update && apt-get install -y libzbar-dev
    - pip install opencv-python pyzbar
    - ln -s /fat-storage/cashier-checks-samples samples

no_filter:
  <<: *temp
  script:
    - python qr.py --dir samples/


filter_zoomer:
  <<: *temp
  script:
    - python qr.py --dir samples/ --filter zoomer

filter_gray:
  <<: *temp
  script:
    - python qr.py --dir samples/ --filter gray

filter_gray_with_zoomer:
  <<: *temp
  script:
    - python qr.py --dir samples/ --filter gray,zoomer


php_basic:
  stage: test
  image: kolyadin/php:7.2
  dependencies: []
  before_script:
    - ln -s /fat-storage/cashier-checks-samples samples
    - composer install
  script:
    - php qr.php
