stages:
  - test

variables:
  PIP_DOWNLOAD_CACHE: "/cache/python-pip"

validation_check:
  stage: test
  image: python:3.7
  dependencies: []
  before_script:
    - ln -s /cache/python-pip ~/.cache/pip
    - apt-get update && apt-get install -y libzbar-dev
    - pip install opencv-python pyzbar
    - ln -s /fat-storage/cashier-checks-samples /var/www/html/samples
  script:
    - cd /var/www/html && python qr.py
