version: '3.7'

services:

  app_cli:
    build:
      context: .docker/python/
    working_dir: /var/www/html/
    command: "/bin/bash -c 'while true; do sleep 30; done;'"
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/www/html/:rw,cached

networks:
  default:
    driver: bridge
